# This workflow builds and deploys a React app to GitHub Pages
name: Build and Deploy React App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
      
      - name: Clean npm cache
        run: npm cache clean --force
      
      # Skip npm update - use the one that comes with Node.js 16
      
      - name: Create Clean node_modules
        run: |
          rm -rf node_modules
          rm -f package-lock.json
      
      - name: Install dependencies
        run: npm install --legacy-peer-deps --no-audit --no-fund
      
      - name: Build
        run: |
          export NODE_OPTIONS=--max_old_space_size=4096
          CI=false GENERATE_SOURCEMAP=false npm run build
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'
        if: success()

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4